version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    # image: ghcr.io/mikecao/umami:mysql-latest
    ports:
      - "3000:3000" #default username admin and password umami
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      # DATABASE_URL: mysql://username:mypassword@localhost:3306/umami
      DATABASE_TYPE: postgresql
      # DATABASE_TYPE: mysql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./umami-db-data:/var/lib/postgresql/data:rw
    restart: always

# volumes:
#   umami-db-data: