version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    # image: ghcr.io/flaresolverr/flaresolverr:latest
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-false}
      # - LOG_HTML=true
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - BROWSER_TIMEOUT=80000
      - TZ=Asia/Shanghai
      - TEST_URL=https://www.baidu.com
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
